### ISSUE TITLE
GP-2 memory map vs. GP memory map

### ISSUE THREAD

**Issue by MDAR** [cedricboon/openhab2-addons#14]
Hi

I saw a question that asked about the difference in the new version of glass panel memory maps.

https://forum.velbus.eu/t/differenc-between-vmbgp-and-vmbgp-2/15853

Is this something that affects any of your work?

**Comment by cedricboon** [comment]
I don't think it does:
- The 8th databyte in the module type packet would currently be ignored
- The binding only interacts directly with the memory map for the alarm configurations, and the addresses of the alarm configuration in the memory map still look the same
