### ISSUE TITLE
Minor typo - Alarm 1 Wakup is missing an E

### ISSUE THREAD

**Issue by MDAR** [cedricboon/openhab2-addons#19]
Hi

A very minor typo which doesn't affect anything.

It appears that `Clock Alarm 1 Wakup Minute` is missing it's 'e'

**Comment by cedricboon** [comment]
Fixed in [Release 2.5.1.202002010925](https://github.com/cedricboon/openhab2-addons/releases/tag/2.5.1.202002010925)
