### ISSUE TITLE
Bug - Problem with alarms on Edge lit modules

### ISSUE THREAD

**Issue by cedricboon** [cedricboon/openhab2-addons#2]

**Comment by MDAR** [comment]
Hi

It appears to be Writing new values to the module (VMBELO), but not reading values at all.

All I see is -NaN

If I disable and re-enable the OLED Edge Lit, I can see if being polled in Velbuslink.,

HabPanel shows 0 for all values on Knob widgets, if I change the value in HabPanel then Read the velbus settting in VelbusLink, the new values are shown in Velbuslink configuration.

**Comment by MDAR** [comment]
However..

Restarting openHAB2 seems to have woken it yup.

It reads the values correctly

and if i change the values in VelbusLink and write them back to the module, openHAB2 sees the changes instantly
