### ISSUE TITLE
Velbus bridge doesnt reconnect to Velserv

### ISSUE THREAD

**Issue by kandersen01** [cedricboon/openhab2-addons#27]
Hi Cedric´.. First of all, thak you very much for your work. I highly appreciate it! I do believe I have run into a small issue though.

I´m running two openhab systems. VelServ is setup on my Odroid running Ubuntu and openhab 2.5.3. Brigde and Vebus devices works just fine. 
My second system is a Rpi 3B+, running openhabian (openhab) 2.5.0 (stable). Bridge and devices running fine as well.
Both systems are using the latest Velbus binding 2.5.2Dev. I use Stuart´s (Mdar) script to get the latest version. 

I just notice, if I reboot the Odroid system, running Velserv, the Velbus bridge on the Rpi looses connection to the Velserv (ofcouse). But it does not reconnect when the Ordoid is up and running again. 

This is what happens on the Rpi:
`2020-04-07 10:25:01.980 [ERROR] [internal.handler.VelbusBridgeHandler] - Bridge write error
	at org.openhab.binding.velbus.internal.handler.VelbusBridgeHandler.writePacket(VelbusBridgeHandler.java:196) ~[?:?]
	at org.openhab.binding.velbus.internal.handler.VelbusBridgeHandler.sendPacket(VelbusBridgeHandler.java:160) ~[?:?]
	at org.openhab.binding.velbus.internal.handler.VelbusBridgeHandler.lambda$1(VelbusBridgeHandler.java:154) ~[?:?]`

Now.. If I enter the Velbus brigde on the Rpi and make a slight update to any of the settings (reconnect setting from default 15 to 20, but anyone will do), as soon as I save the new setting, the Bridge will connect just fine, and all devices are up running again. 

`2020-04-07 10:27:36.067 [me.event.ThingUpdatedEvent] - Thing 'velbus:networkbridge:93a20e7d' has been updated.
2020-04-07 10:27:36.077 [hingStatusInfoChangedEvent] - 'velbus:networkbridge:93a20e7d' changed from OFFLINE (COMMUNICATION_ERROR): A network communication error occurred. to ONLINE
2020-04-07 10:27:36.094 [hingStatusInfoChangedEvent] - 'velbus:vmbelo:93a20e7d:02' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2020-04-07 10:27:36.105 [hingStatusInfoChangedEvent] - 'velbus:vmb4ryno:93a20e7d:03' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2020-04-07 10:27:36.114 [hingStatusInfoChangedEvent] - 'velbus:vmb4dc:93a20e7d:05' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2020-04-07 10:27:36.121 [hingStatusInfoChangedEvent] - 'velbus:vmb1rynos:93a20e7d:01' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2020-04-07 10:27:36.172 [hingStatusInfoChangedEvent] - 'velbus:vmbgp4:93a20e7d:74' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE`

I can reproduce this issue just by rebooting my Odroid/Velserv system

Greets
Kim

**Comment by MDAR** [comment]
Hi

Have you tried updating the Velbus binding recently and checking in Karaf that only the latest is loaded?

This behaviour should be fixed.
(Subject to the reconnection setting in the bridge)

**Comment by MDAR** [comment]
Hi Kim

Can you confirm that everything is workin correctly now and close this issue please?

**Comment by kandersen01** [comment]
> Hi Kim
> 
> Can you confirm that everything is workin correctly now and close this issue please?

Unfortunatly not, Stuart. And the issue has gone worse after I updated my openhab system (on the Rpi3B+), cause I can no longer enter the Velbus Bridge settings at all I get a blank screen on the parameters.. 
When I try to add a new bridge I can only add serial and not ip adress for the velbus server, (which is running on the Odroid C2 system). There are no option for adding the IP adress. 

Atm I´m using Velbus binding 2.5.6 on my Rpi system and Velbus binding 2.5.5 on my Odroid system. I can not get my Rpi system to connect to the Velserver on my Odroid system. And it may be due to other causes.

Sorry this isnt much help, I know :-(

**Comment by MDAR** [comment]
Try adding a Velbus Network Bridge :-)


I hope you know I'm happy to help.

**Comment by kandersen01** [comment]
Wish I could, but its not there in the 2.5.6 binding.. (that would explain howcome I cant add it.. Hmprf!!). 

I know you´re here to help, as usual.. I have just been occupied with several other openhab issues lately..

**Comment by MDAR** [comment]
I haven't used the binding from the common repository.

I think it's still the very first version that Cédric submitted (I could be wrong)

May I suggest you use the one from this repository, or from my website (should be the same)

**Comment by MDAR** [comment]
@kandersen01 

Have you had a chance to try the lastest Velbus binding, to confirm that the recoonect feature is working?

If so, can you close this issue?

**Comment by kandersen01** [comment]
> @kandersen01
> 
> Have you had a chance to try the lastest Velbus binding, to confirm that the recoonect feature is working?
> 
> If so, can you close this issue?

Yes it works. Issue kan be closed.

**Comment by MDAR** [comment]
Thanks @kandersen01 

You need to close the issue, because you opened it

**Comment by kandersen01** [comment]
Lol.. Guess Christmas isn´t all over yet :-D
