### ISSUE TITLE
VMBVP01 - Door bird module

### ISSUE THREAD

**Issue by MDAR** [cedricboon/openhab2-addons#32]
Hi

Further to CobelS' request on the Velbus forum.

When you have time, can you add the DoorBird VMBVP01 module to the binidng.

https://forum.velbus.eu/t/velbus-binding-for-openhab/14992/246

From what I can see, it is just a basic module, with the 8 button events, without LED feedback,
(it very probably has the alarm clock function, but I don't have one so can't confirm this)

Many thanks

Stuart

**Comment by cedricboon** [comment]
Added in commit #8f603bc79dcc849f9933cfc18a10952ad31ad1c7
